baseURL = '/'
languageCode = 'en-us'
title = 'explain, analyze'
theme = 'hello-friend-ng'
enableGitInfo = true
paginate = 10

[params]
customCSS = ["/css/custom.css"]

[params.Logo]
logoText = "explain, analyze"

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
